-- MySQL Script generated by MySQL Workbench
-- Sun Mar  1 21:33:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LFJ
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LFJ
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LFJ` DEFAULT CHARACTER SET utf8 ;
USE `LFJ` ;

-- -----------------------------------------------------
-- Table `LFJ`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LFJ`.`user` ;

CREATE TABLE IF NOT EXISTS `LFJ`.`user` (
  `user_id` INT NOT NULL,
  `display_name` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NULL,
  `admin` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFJ`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LFJ`.`game` ;

CREATE TABLE IF NOT EXISTS `LFJ`.`game` (
  `game_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`game_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFJ`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LFJ`.`event` ;

CREATE TABLE IF NOT EXISTS `LFJ`.`event` (
  `event_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFJ`.`membership`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LFJ`.`membership` ;

CREATE TABLE IF NOT EXISTS `LFJ`.`membership` (
  `user_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  `skill_level` INT NOT NULL,
  PRIMARY KEY (`user_id`, `game_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFJ`.`registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LFJ`.`registration` ;

CREATE TABLE IF NOT EXISTS `LFJ`.`registration` (
  `user_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`, `event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LFJ`.`performance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LFJ`.`performance` ;

CREATE TABLE IF NOT EXISTS `LFJ`.`performance` (
  `user_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `kills` INT NOT NULL,
  `deaths` INT NOT NULL,
  `win` INT NOT NULL,
  `length` INT NOT NULL,
  `win_score` INT NOT NULL,
  `lose_score` INT NOT NULL,
  PRIMARY KEY (`user_id`, `event_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `LFJ`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `LFJ`;
INSERT INTO `LFJ`.`user` (`user_id`, `display_name`, `e-mail`, `admin`) VALUES (8494, 'jon_wiseman#8494', 'wisemanj@etown.edu', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `LFJ`.`game`
-- -----------------------------------------------------
START TRANSACTION;
USE `LFJ`;
INSERT INTO `LFJ`.`game` (`game_id`, `name`) VALUES (0, 'League of Legends');
INSERT INTO `LFJ`.`game` (`game_id`, `name`) VALUES (1, 'Counter Strike: Global Offensive');
INSERT INTO `LFJ`.`game` (`game_id`, `name`) VALUES (2, 'Rocket League');

COMMIT;


-- -----------------------------------------------------
-- Data for table `LFJ`.`membership`
-- -----------------------------------------------------
START TRANSACTION;
USE `LFJ`;
INSERT INTO `LFJ`.`membership` (`user_id`, `game_id`, `skill_level`) VALUES (8494, 0, 0);
INSERT INTO `LFJ`.`membership` (`user_id`, `game_id`, `skill_level`) VALUES (8494, 1, 100);

COMMIT;

